export const RAW_MAP = [
    { name:"출발", type:"start", cost:0 },
    { name:"방콕", type:"city", cost:10, group:"#a29bfe" },
    { name:"찬스", type:"chance", cost:0 },
    { name:"베이징", type:"city", cost:15, group:"#a29bfe" },
    { name:"마닐라", type:"city", cost:15, group:"#a29bfe" },
    { name:"제주", type:"city", cost:20, group:"#74b9ff" },
    { name:"타이페이", type:"city", cost:25, group:"#74b9ff" },
    { name:"찬스", type:"chance", cost:0 },
    { name:"홍콩", type:"city", cost:28, group:"#74b9ff" },
    { name:"상하이", type:"city", cost:30, group:"#74b9ff" },
    { name:"무인도", type:"island", cost:0 },
    { name:"아테네", type:"city", cost:35, group:"#55efc4" },
    { name:"찬스", type:"chance", cost:0 },
    { name:"코펜하겐", type:"city", cost:38, group:"#55efc4" },
    { name:"이스탄불", type:"city", cost:40, group:"#55efc4" },
    { name:"부산", type:"city", cost:45, group:"#81ecec" },
    { name:"베를린", type:"city", cost:50, group:"#fab1a0" },
    { name:"찬스", type:"chance", cost:0 },
    { name:"몬트리올", type:"city", cost:55, group:"#fab1a0" },
    { name:"취리히", type:"city", cost:60, group:"#fab1a0" },
    { name:"올림픽", type:"olympic", cost:0 },
    { name:"시드니", type:"city", cost:65, group:"#ffeaa7" },
    { name:"찬스", type:"chance", cost:0 },
    { name:"하와이", type:"city", cost:70, group:"#ffeaa7" },
    { name:"상파울루", type:"city", cost:75, group:"#ffeaa7" },
    { name:"오사카", type:"city", cost:80, group:"#ff7675" },
    { name:"프라하", type:"city", cost:85, group:"#ff7675" },
    { name:"찬스", type:"chance", cost:0 },
    { name:"리스본", type:"city", cost:90, group:"#ff7675" },
    { name:"마드리드", type:"city", cost:95, group:"#ff7675" },
    { name:"우주여행", type:"travel", cost:0 },
    { name:"도쿄", type:"city", cost:100, group:"#636e72" },
    { name:"파리", type:"city", cost:110, group:"#636e72" },
    { name:"로마", type:"city", cost:120, group:"#636e72" },
    { name:"찬스", type:"chance", cost:0 },
    { name:"런던", type:"city", cost:130, group:"#0984e3" },
    { name:"뉴욕", type:"city", cost:140, group:"#0984e3" },
    { name:"국세청", type:"tax", cost:0 },
    { name:"서울", type:"city", cost:150, group:"#0984e3" },
];
// 맵 데이터 40칸 보정
while(RAW_MAP.length < 40) RAW_MAP.push({name:"오류", type:"chance", cost:0});

export const COST_RATIO = { land:1, villa:0.5, building:1.0, hotel:2.0, landmark:4.0 };
export const TOLL_RATIO = { land:0.5, villa:1.5, building:3.0, hotel:6.0, landmark:15.0 };
